name = "2t4"
compatibility_date = "2023-10-30"
send_metrics = false
node_compat = true
route = "https://2t4.pages.dev/*"
workers_dev = false

[env.preview]
name = "t4-stack-preview"
workers_dev = true
